# #####################################################################
# Automatically generated by qmake (2.01a) Wed May 5 09:04:35 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    debug \
    release
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp \
    widget.cpp
RESOURCES += images.qrc
