s3c24xx_lcd_test:s3c24xx_lcd_test.o lcd.o
	arm-linux-gcc -o s3c24xx_lcd_test s3c24xx_lcd_test.o lcd.o
s3c24xx_lcd_test.o:s3c24xx_lcd_test.c 
	arm-linux-gcc -c  s3c24xx_lcd_test.c
lcd.o:lcd.c
	arm-linux-gcc -c lcd.c
